#!/bin/sh
#
# Script to build container image.
#

SCRIPT_DIR=$(cd -- "$(dirname -- "${0}")" && pwd)
. "${SCRIPT_DIR}/inc.functions"

# Default values
DEFAULT_BASE=$(grep base= "${SCRIPT_DIR}/../Dockerfile" | cut -d"=" -f2)
DEFAULT_TOOL=$( (command -v docker || command -v podman) | grep -o '[^/]*$')
DEFAULT_PLATFORMS="linux/amd64,linux/arm64"

# Functions
usage() {
  printf "Usage: %s [OPTIONS]\n" "${0}"
  printf "Options:\n"
  printf "  --base VERSION  (default: %s)\n" "${DEFAULT_BASE}"
  printf "  --docker        (optional, build with Docker)"
  printf "  --platforms     (default: %s)\n" "${DEFAULT_PLATFORMS}"
  printf "  --podman        (optional, build with Podman)"
  printf "  --push          (optional, upload images to Docker Hub)\n"
  printf "  --verbose       (optional)\n"
  exit 1
}

# Command-line arguments
base="${DEFAULT_BASE}"
platforms="${DEFAULT_PLATFORMS}"
cmd_push=
progress=auto
tool="${DEFAULT_TOOL}"
while [ $# -gt 0 ]; do
  key="$1"
  case $key in
  --base) base="$2" shift ;; # past argument
  --docker) tool="docker" ;;
  --platforms) platforms="$2" shift ;; # past argument
  --podman) tool="podman" ;;
  --push) cmd_push=true ;;
  --verbose) progress=plain ;;
  -h | --help) usage ;;
  *) ;; # unknown option
  esac
  shift # past argument or value
done

# Let's roll
image_tag="saschpe/renovate-helm-docs:${base}"

if [ ${cmd_push} ]; then
  approve "Build and push image '${image_tag}' with ${tool}"
  push_command="--push"
else
  approve "Build image '${image_tag}' with ${tool}"
fi

safe "${tool}" build \
  --build-arg base="${base}" \
  --platform "${platforms}" \
  --progress "${progress}" \
  ${push_command} \
  --tag "${image_tag}" \
  .
